name: Terraform Format and Validate

on: 
  workflow_dispatch:

  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write
      
jobs:
  terraform-format-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Pull request comment
        run: |
            gh api --method POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/$GITHUB_REPOSITORY/issues/${{ github.event.number }}/comments \
                -f "body=New PR has been created."

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate
