name: Terraform Format and Validate

on: 
  workflow_dispatch:

  pull_request:
    branches:
    - main

permissions:
  contents: read
  pull-requests: write
  issues: write
      
jobs:
  terraform-format-and-validate:
    env:
      GH_TOKEN: ${{ github.token }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      id: terraform-format
      run: terraform fmt -check

    - name: Pull request comment for format check
      if: ${{ failure() && steps.terraform-format.outcome == 'failure' }}
      run: |
        gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$GITHUB_REPOSITORY/issues/${{ github.event.number }}/comments \
            -f "body=Terraform format check failed.<br>Please run 'terraform fmt' and push the changes to the PR.<br>For more information, refer to the [Terraform format documentation](https://www.terraform.io/docs/commands/fmt.html)"

    - name: Terraform Validate
      id: terraform-validate
      if: always()
      run: terraform validate

    - name: Pull request comment for validate check
      if: ${{ failure() && steps.terraform-validate.outcome == 'failure' }}
      run: |
        gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$GITHUB_REPOSITORY/issues/${{ github.event.number }}/comments \
            -f "body=Terraform validate check failed.<br>Please review the errors in the failed check, make corrections, and push the changes to the PR.<br>For more information, refer to the [Terraform validate documentation](https://www.terraform.io/docs/commands/validate.html)<br>${{ steps.terraform-validate.outputs.stdout }}"
